In [40]:
import numpy as np

In [41]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [42]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [43]:
num_rows, num_cols = a.shape
num_rows

5

In [44]:
mean_a = a.mean(axis=0)

In [45]:
mean_a

array([2. , 8.4])

In [46]:
a_centered = a - mean_a

In [47]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [48]:
a_centered_tr = a_centered.transpose()

In [49]:
a_centered_tr

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [50]:
a_centered_1, a_centered_2 = np.vsplit(a_centered_tr,2)

In [51]:
a_centered_1 = np.squeeze(a_centered_1)
a_centered_1

array([-1.,  0.,  1.,  1., -1.])

In [52]:
a_centered_2 = np.squeeze(a_centered_2)
a_centered_2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [53]:
a_centered_sp = np.dot(a_centered_1,a_centered_2)
a_centered_sp

8.0

In [54]:
result = a_centered_sp/(num_rows-1)
result

2.0

In [55]:
a_centered_tr
result_1 = np.cov(a_centered_tr)
result_1

array([[1. , 2. ],
       [2. , 4.3]])

In [56]:
result_1[0][1] == result

True